name: Test Go Project

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: copy google-application-credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_SECRET: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo $GOOGLE_APPLICATION_CREDENTIALS_SECRET | base64 --decode --ignore-garbage > /tmp/google-application-credentials

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code into the go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Check Env
        env:
          UID: ${{ secrets.UID }}
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-application-credentials
        run: |
          CGO_ENABLED=0 GOOS=linux go test -v ./...