name: Test Go Project

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: copy google-application-credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_SECRET: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo $GOOGLE_APPLICATION_CREDENTIALS_SECRET | base64 --decode --ignore-garbage > ./firebase_adminsdk.json

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code into the go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Check Firebase_adminsdk path
        run: echo $(find `pwd` -name firebase_adminsdk.json)

      - name: Test Code
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(find `pwd` -name firebase_adminsdk.json)" >> $GITHUB_ENV

      - name: Check Env
        env:
          UID: ${{ secrets.UID }}
        run: |
          CGO_ENABLED=0 GOOS=linux go test -v ./...
#        run: export GOOGLE_APPLICATION_CREDENTIALS=$(find `pwd` -name firebase_adminsdk.json) && CGO_ENABLED=0 GOOS=linux go test -v ./...